apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: test111
build:
  artifacts:
    - image: jem2305/test111
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}