apiVersion: apps/v1
kind: Deployment
metadata:
  name: test111
spec:
  selector:
    matchLabels:
      app: test111
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: test111
    spec:
      containers:
        - name: test111
          image: jem2305/test111
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test111
spec:
  type: NodePort
  selector:
    app: test111
  ports:
    - port: 8080
      nodePort: 30000